# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crd_gui_design.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(998, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_artists = QtWidgets.QWidget()
        self.tab_artists.setObjectName("tab_artists")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_artists)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitterArtists = QtWidgets.QSplitter(self.tab_artists)
        self.splitterArtists.setOrientation(QtCore.Qt.Horizontal)
        self.splitterArtists.setObjectName("splitterArtists")
        self.treeArtists = QtWidgets.QTreeView(self.splitterArtists)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeArtists.sizePolicy().hasHeightForWidth())
        self.treeArtists.setSizePolicy(sizePolicy)
        self.treeArtists.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeArtists.setObjectName("treeArtists")
        self.treeArtists.header().setVisible(False)
        self.viewerArtists = QtWidgets.QTextBrowser(self.splitterArtists)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewerArtists.sizePolicy().hasHeightForWidth())
        self.viewerArtists.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.viewerArtists.setFont(font)
        self.viewerArtists.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.viewerArtists.setObjectName("viewerArtists")
        self.verticalLayout_2.addWidget(self.splitterArtists)
        self.tabWidget.addTab(self.tab_artists, "")
        self.tab_tunings = QtWidgets.QWidget()
        self.tab_tunings.setObjectName("tab_tunings")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_tunings)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitterTunings = QtWidgets.QSplitter(self.tab_tunings)
        self.splitterTunings.setOrientation(QtCore.Qt.Horizontal)
        self.splitterTunings.setObjectName("splitterTunings")
        self.treeTunings = QtWidgets.QTreeView(self.splitterTunings)
        self.treeTunings.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeTunings.setObjectName("treeTunings")
        self.treeTunings.header().setVisible(False)
        self.viewerTunings = QtWidgets.QTextBrowser(self.splitterTunings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewerTunings.sizePolicy().hasHeightForWidth())
        self.viewerTunings.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.viewerTunings.setFont(font)
        self.viewerTunings.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.viewerTunings.setObjectName("viewerTunings")
        self.verticalLayout_3.addWidget(self.splitterTunings)
        self.tabWidget.addTab(self.tab_tunings, "")
        self.tab_search = QtWidgets.QWidget()
        self.tab_search.setObjectName("tab_search")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_search)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_search)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.checkLyrics = QtWidgets.QCheckBox(self.tab_search)
        self.checkLyrics.setChecked(True)
        self.checkLyrics.setObjectName("checkLyrics")
        self.horizontalLayout_5.addWidget(self.checkLyrics)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.splitterSearch = QtWidgets.QSplitter(self.tab_search)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitterSearch.sizePolicy().hasHeightForWidth())
        self.splitterSearch.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.splitterSearch.setFont(font)
        self.splitterSearch.setOrientation(QtCore.Qt.Horizontal)
        self.splitterSearch.setObjectName("splitterSearch")
        self.treeSearch = QtWidgets.QTreeView(self.splitterSearch)
        self.treeSearch.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.treeSearch.setObjectName("treeSearch")
        self.treeSearch.header().setVisible(False)
        self.viewerSearch = QtWidgets.QTextBrowser(self.splitterSearch)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewerSearch.sizePolicy().hasHeightForWidth())
        self.viewerSearch.setSizePolicy(sizePolicy)
        self.viewerSearch.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.viewerSearch.setObjectName("viewerSearch")
        self.verticalLayout_7.addWidget(self.splitterSearch)
        self.verticalLayout_5.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.tab_search, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chordFind = QtWidgets.QPushButton(self.tab)
        self.chordFind.setObjectName("chordFind")
        self.horizontalLayout_2.addWidget(self.chordFind)
        self.chordName = QtWidgets.QLineEdit(self.tab)
        self.chordName.setObjectName("chordName")
        self.horizontalLayout_2.addWidget(self.chordName)
        self.tuningCombo = QtWidgets.QComboBox(self.tab)
        self.tuningCombo.setMinimumSize(QtCore.QSize(400, 0))
        self.tuningCombo.setObjectName("tuningCombo")
        self.horizontalLayout_2.addWidget(self.tuningCombo)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.chordResult1 = QtWidgets.QTextEdit(self.tab)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.chordResult1.setFont(font)
        self.chordResult1.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.chordResult1.setObjectName("chordResult1")
        self.verticalLayout_8.addWidget(self.chordResult1)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.tabWidget.addTab(self.tab, "")
        self.tab_import = QtWidgets.QWidget()
        self.tab_import.setObjectName("tab_import")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_import)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.importEdit = QtWidgets.QLineEdit(self.tab_import)
        self.importEdit.setObjectName("importEdit")
        self.verticalLayout_4.addWidget(self.importEdit)
        self.splitter = QtWidgets.QSplitter(self.tab_import)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.splitter.setFont(font)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.treeImport = QtWidgets.QTreeView(self.splitter)
        self.treeImport.setHeaderHidden(True)
        self.treeImport.setObjectName("treeImport")
        self.viewerImport = QtWidgets.QTextBrowser(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewerImport.sizePolicy().hasHeightForWidth())
        self.viewerImport.setSizePolicy(sizePolicy)
        self.viewerImport.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.viewerImport.setObjectName("viewerImport")
        self.verticalLayout_4.addWidget(self.splitter)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_import, "")
        self.tab_settings = QtWidgets.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.comboCommentColour = QtWidgets.QComboBox(self.tab_settings)
        self.comboCommentColour.setGeometry(QtCore.QRect(160, 20, 181, 21))
        self.comboCommentColour.setObjectName("comboCommentColour")
        self.label_1 = QtWidgets.QLabel(self.tab_settings)
        self.label_1.setGeometry(QtCore.QRect(20, 20, 121, 17))
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.tab_settings)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 101, 17))
        self.label_2.setObjectName("label_2")
        self.comboChordColour = QtWidgets.QComboBox(self.tab_settings)
        self.comboChordColour.setGeometry(QtCore.QRect(160, 50, 181, 21))
        self.comboChordColour.setObjectName("comboChordColour")
        self.label_3 = QtWidgets.QLabel(self.tab_settings)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 121, 17))
        self.label_3.setObjectName("label_3")
        self.comboTabColour = QtWidgets.QComboBox(self.tab_settings)
        self.comboTabColour.setGeometry(QtCore.QRect(160, 80, 181, 21))
        self.comboTabColour.setObjectName("comboTabColour")
        self.hideComment = QtWidgets.QCheckBox(self.tab_settings)
        self.hideComment.setGeometry(QtCore.QRect(360, 20, 99, 22))
        self.hideComment.setObjectName("hideComment")
        self.hideChord = QtWidgets.QCheckBox(self.tab_settings)
        self.hideChord.setGeometry(QtCore.QRect(360, 50, 99, 22))
        self.hideChord.setObjectName("hideChord")
        self.hideTab = QtWidgets.QCheckBox(self.tab_settings)
        self.hideTab.setGeometry(QtCore.QRect(360, 80, 99, 22))
        self.hideTab.setObjectName("hideTab")
        self.tabWidget.addTab(self.tab_settings, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.reloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.reloadButton.setObjectName("reloadButton")
        self.horizontalLayout.addWidget(self.reloadButton)
        self.editButton = QtWidgets.QPushButton(self.centralwidget)
        self.editButton.setEnabled(False)
        self.editButton.setObjectName("editButton")
        self.horizontalLayout.addWidget(self.editButton)
        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setEnabled(False)
        self.playButton.setObjectName("playButton")
        self.horizontalLayout.addWidget(self.playButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 998, 25))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.treeArtists.clicked['QModelIndex'].connect(MainWindow.treeIndexClicked)
        self.treeTunings.clicked['QModelIndex'].connect(MainWindow.treeIndexClicked)
        self.treeSearch.clicked['QModelIndex'].connect(MainWindow.treeIndexClicked)
        self.treeImport.clicked['QModelIndex'].connect(MainWindow.treeIndexClicked)
        self.viewerArtists.anchorClicked['QUrl'].connect(MainWindow.viewerLinkClicked)
        self.viewerImport.anchorClicked['QUrl'].connect(MainWindow.viewerLinkClicked)
        self.viewerSearch.anchorClicked['QUrl'].connect(MainWindow.viewerLinkClicked)
        self.viewerTunings.anchorClicked['QUrl'].connect(MainWindow.viewerLinkClicked)
        self.playButton.clicked.connect(MainWindow.playButtonClicked)
        self.tabWidget.currentChanged['int'].connect(MainWindow.tabChanged)
        self.comboChordColour.currentIndexChanged['int'].connect(MainWindow.settingsChanged)
        self.comboCommentColour.currentIndexChanged['int'].connect(MainWindow.settingsChanged)
        self.checkLyrics.clicked['bool'].connect(MainWindow.searchLyricsChanged)
        self.chordFind.clicked.connect(MainWindow.lookupChord)
        self.chordName.returnPressed.connect(MainWindow.lookupChord)
        self.editButton.clicked.connect(MainWindow.editButtonClicked)
        self.reloadButton.clicked.connect(MainWindow.reloadButtonClicked)
        self.comboTabColour.currentIndexChanged['int'].connect(MainWindow.settingsChanged)
        self.hideChord.clicked.connect(MainWindow.settingsChanged)
        self.hideComment.clicked.connect(MainWindow.settingsChanged)
        self.hideTab.clicked.connect(MainWindow.settingsChanged)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chord Explorer"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_artists), _translate("MainWindow", "Artists"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tunings), _translate("MainWindow", "Tunings"))
        self.checkLyrics.setText(_translate("MainWindow", "Lyrics"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_search), _translate("MainWindow", "Search"))
        self.chordFind.setText(_translate("MainWindow", "Find"))
        self.chordName.setPlaceholderText(_translate("MainWindow", "Chord name"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Chords"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_import), _translate("MainWindow", "Import"))
        self.label_1.setText(_translate("MainWindow", "Comment colour"))
        self.label_2.setText(_translate("MainWindow", "Chord colour"))
        self.label_3.setText(_translate("MainWindow", "Tablature colour"))
        self.hideComment.setText(_translate("MainWindow", "Hide"))
        self.hideChord.setText(_translate("MainWindow", "Hide"))
        self.hideTab.setText(_translate("MainWindow", "Hide"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_settings), _translate("MainWindow", "Settings"))
        self.reloadButton.setText(_translate("MainWindow", "Reload"))
        self.editButton.setText(_translate("MainWindow", "Edit"))
        self.playButton.setText(_translate("MainWindow", "Play"))

