# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crd_gui_design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(998, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_artists = QtGui.QWidget()
        self.tab_artists.setObjectName(_fromUtf8("tab_artists"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_artists)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitterArtists = QtGui.QSplitter(self.tab_artists)
        self.splitterArtists.setOrientation(QtCore.Qt.Horizontal)
        self.splitterArtists.setObjectName(_fromUtf8("splitterArtists"))
        self.treeArtists = QtGui.QTreeView(self.splitterArtists)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeArtists.sizePolicy().hasHeightForWidth())
        self.treeArtists.setSizePolicy(sizePolicy)
        self.treeArtists.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeArtists.setObjectName(_fromUtf8("treeArtists"))
        self.treeArtists.header().setVisible(False)
        self.viewerArtists = QtGui.QTextBrowser(self.splitterArtists)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewerArtists.sizePolicy().hasHeightForWidth())
        self.viewerArtists.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        self.viewerArtists.setFont(font)
        self.viewerArtists.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.viewerArtists.setObjectName(_fromUtf8("viewerArtists"))
        self.verticalLayout_2.addWidget(self.splitterArtists)
        self.tabWidget.addTab(self.tab_artists, _fromUtf8(""))
        self.tab_tunings = QtGui.QWidget()
        self.tab_tunings.setObjectName(_fromUtf8("tab_tunings"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_tunings)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.splitterTunings = QtGui.QSplitter(self.tab_tunings)
        self.splitterTunings.setOrientation(QtCore.Qt.Horizontal)
        self.splitterTunings.setObjectName(_fromUtf8("splitterTunings"))
        self.treeTunings = QtGui.QTreeView(self.splitterTunings)
        self.treeTunings.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeTunings.setObjectName(_fromUtf8("treeTunings"))
        self.treeTunings.header().setVisible(False)
        self.viewerTunings = QtGui.QTextBrowser(self.splitterTunings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewerTunings.sizePolicy().hasHeightForWidth())
        self.viewerTunings.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        self.viewerTunings.setFont(font)
        self.viewerTunings.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.viewerTunings.setObjectName(_fromUtf8("viewerTunings"))
        self.verticalLayout_3.addWidget(self.splitterTunings)
        self.tabWidget.addTab(self.tab_tunings, _fromUtf8(""))
        self.tab_search = QtGui.QWidget()
        self.tab_search.setObjectName(_fromUtf8("tab_search"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_search)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lineEdit = QtGui.QLineEdit(self.tab_search)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.checkLyrics = QtGui.QCheckBox(self.tab_search)
        self.checkLyrics.setObjectName(_fromUtf8("checkLyrics"))
        self.horizontalLayout_5.addWidget(self.checkLyrics)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.splitterSearch = QtGui.QSplitter(self.tab_search)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitterSearch.sizePolicy().hasHeightForWidth())
        self.splitterSearch.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        self.splitterSearch.setFont(font)
        self.splitterSearch.setOrientation(QtCore.Qt.Horizontal)
        self.splitterSearch.setObjectName(_fromUtf8("splitterSearch"))
        self.treeSearch = QtGui.QTreeView(self.splitterSearch)
        self.treeSearch.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeSearch.setObjectName(_fromUtf8("treeSearch"))
        self.treeSearch.header().setVisible(False)
        self.viewerSearch = QtGui.QTextBrowser(self.splitterSearch)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewerSearch.sizePolicy().hasHeightForWidth())
        self.viewerSearch.setSizePolicy(sizePolicy)
        self.viewerSearch.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.viewerSearch.setObjectName(_fromUtf8("viewerSearch"))
        self.verticalLayout_7.addWidget(self.splitterSearch)
        self.verticalLayout_5.addLayout(self.verticalLayout_7)
        self.tabWidget.addTab(self.tab_search, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.chordFind = QtGui.QPushButton(self.tab)
        self.chordFind.setObjectName(_fromUtf8("chordFind"))
        self.horizontalLayout_2.addWidget(self.chordFind)
        self.chordName = QtGui.QLineEdit(self.tab)
        self.chordName.setObjectName(_fromUtf8("chordName"))
        self.horizontalLayout_2.addWidget(self.chordName)
        self.tuningCombo = QtGui.QComboBox(self.tab)
        self.tuningCombo.setMinimumSize(QtCore.QSize(400, 0))
        self.tuningCombo.setObjectName(_fromUtf8("tuningCombo"))
        self.horizontalLayout_2.addWidget(self.tuningCombo)
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.chordResult1 = QtGui.QTextEdit(self.tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        self.chordResult1.setFont(font)
        self.chordResult1.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.chordResult1.setObjectName(_fromUtf8("chordResult1"))
        self.verticalLayout_8.addWidget(self.chordResult1)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_import = QtGui.QWidget()
        self.tab_import.setObjectName(_fromUtf8("tab_import"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_import)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.importEdit = QtGui.QLineEdit(self.tab_import)
        self.importEdit.setObjectName(_fromUtf8("importEdit"))
        self.verticalLayout_4.addWidget(self.importEdit)
        self.splitter = QtGui.QSplitter(self.tab_import)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        self.splitter.setFont(font)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.treeImport = QtGui.QTreeView(self.splitter)
        self.treeImport.setHeaderHidden(True)
        self.treeImport.setObjectName(_fromUtf8("treeImport"))
        self.viewerImport = QtGui.QTextBrowser(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewerImport.sizePolicy().hasHeightForWidth())
        self.viewerImport.setSizePolicy(sizePolicy)
        self.viewerImport.setLineWrapMode(QtGui.QTextEdit.NoWrap)
        self.viewerImport.setObjectName(_fromUtf8("viewerImport"))
        self.verticalLayout_4.addWidget(self.splitter)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tab_import, _fromUtf8(""))
        self.tab_settings = QtGui.QWidget()
        self.tab_settings.setObjectName(_fromUtf8("tab_settings"))
        self.comboCommentColour = QtGui.QComboBox(self.tab_settings)
        self.comboCommentColour.setGeometry(QtCore.QRect(160, 20, 181, 21))
        self.comboCommentColour.setObjectName(_fromUtf8("comboCommentColour"))
        self.label_1 = QtGui.QLabel(self.tab_settings)
        self.label_1.setGeometry(QtCore.QRect(20, 20, 121, 17))
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.label_2 = QtGui.QLabel(self.tab_settings)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 101, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.comboChordColour = QtGui.QComboBox(self.tab_settings)
        self.comboChordColour.setGeometry(QtCore.QRect(160, 50, 181, 21))
        self.comboChordColour.setObjectName(_fromUtf8("comboChordColour"))
        self.label_3 = QtGui.QLabel(self.tab_settings)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 121, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.comboTabColour = QtGui.QComboBox(self.tab_settings)
        self.comboTabColour.setGeometry(QtCore.QRect(160, 80, 181, 21))
        self.comboTabColour.setObjectName(_fromUtf8("comboTabColour"))
        self.hideComment = QtGui.QCheckBox(self.tab_settings)
        self.hideComment.setGeometry(QtCore.QRect(360, 20, 99, 22))
        self.hideComment.setObjectName(_fromUtf8("hideComment"))
        self.hideChord = QtGui.QCheckBox(self.tab_settings)
        self.hideChord.setGeometry(QtCore.QRect(360, 50, 99, 22))
        self.hideChord.setObjectName(_fromUtf8("hideChord"))
        self.hideTab = QtGui.QCheckBox(self.tab_settings)
        self.hideTab.setGeometry(QtCore.QRect(360, 80, 99, 22))
        self.hideTab.setObjectName(_fromUtf8("hideTab"))
        self.tabWidget.addTab(self.tab_settings, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.reloadButton = QtGui.QPushButton(self.centralwidget)
        self.reloadButton.setObjectName(_fromUtf8("reloadButton"))
        self.horizontalLayout.addWidget(self.reloadButton)
        self.editButton = QtGui.QPushButton(self.centralwidget)
        self.editButton.setEnabled(False)
        self.editButton.setObjectName(_fromUtf8("editButton"))
        self.horizontalLayout.addWidget(self.editButton)
        self.playButton = QtGui.QPushButton(self.centralwidget)
        self.playButton.setEnabled(False)
        self.playButton.setObjectName(_fromUtf8("playButton"))
        self.horizontalLayout.addWidget(self.playButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 998, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        MainWindow.setMenuBar(self.menuBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.treeArtists, QtCore.SIGNAL(_fromUtf8("clicked(QModelIndex)")), MainWindow.treeIndexClicked)
        QtCore.QObject.connect(self.treeTunings, QtCore.SIGNAL(_fromUtf8("clicked(QModelIndex)")), MainWindow.treeIndexClicked)
        QtCore.QObject.connect(self.treeSearch, QtCore.SIGNAL(_fromUtf8("clicked(QModelIndex)")), MainWindow.treeIndexClicked)
        QtCore.QObject.connect(self.treeImport, QtCore.SIGNAL(_fromUtf8("clicked(QModelIndex)")), MainWindow.treeIndexClicked)
        QtCore.QObject.connect(self.viewerArtists, QtCore.SIGNAL(_fromUtf8("anchorClicked(QUrl)")), MainWindow.viewerLinkClicked)
        QtCore.QObject.connect(self.viewerImport, QtCore.SIGNAL(_fromUtf8("anchorClicked(QUrl)")), MainWindow.viewerLinkClicked)
        QtCore.QObject.connect(self.viewerSearch, QtCore.SIGNAL(_fromUtf8("anchorClicked(QUrl)")), MainWindow.viewerLinkClicked)
        QtCore.QObject.connect(self.viewerTunings, QtCore.SIGNAL(_fromUtf8("anchorClicked(QUrl)")), MainWindow.viewerLinkClicked)
        QtCore.QObject.connect(self.playButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.playButtonClicked)
        QtCore.QObject.connect(self.tabWidget, QtCore.SIGNAL(_fromUtf8("currentChanged(int)")), MainWindow.tabChanged)
        QtCore.QObject.connect(self.comboChordColour, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.settingsChanged)
        QtCore.QObject.connect(self.comboCommentColour, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.settingsChanged)
        QtCore.QObject.connect(self.checkLyrics, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), MainWindow.searchLyricsChanged)
        QtCore.QObject.connect(self.chordFind, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.lookupChord)
        QtCore.QObject.connect(self.chordName, QtCore.SIGNAL(_fromUtf8("returnPressed()")), MainWindow.lookupChord)
        QtCore.QObject.connect(self.editButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.editButtonClicked)
        QtCore.QObject.connect(self.reloadButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.reloadButtonClicked)
        QtCore.QObject.connect(self.comboTabColour, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), MainWindow.settingsChanged)
        QtCore.QObject.connect(self.hideChord, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.settingsChanged)
        QtCore.QObject.connect(self.hideComment, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.settingsChanged)
        QtCore.QObject.connect(self.hideTab, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.settingsChanged)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Chord Explorer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_artists), _translate("MainWindow", "Artists", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tunings), _translate("MainWindow", "Tunings", None))
        self.checkLyrics.setText(_translate("MainWindow", "Lyrics", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_search), _translate("MainWindow", "Search", None))
        self.chordFind.setText(_translate("MainWindow", "Find", None))
        self.chordName.setPlaceholderText(_translate("MainWindow", "Chord name", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Chords", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_import), _translate("MainWindow", "Import", None))
        self.label_1.setText(_translate("MainWindow", "Comment colour", None))
        self.label_2.setText(_translate("MainWindow", "Chord colour", None))
        self.label_3.setText(_translate("MainWindow", "Tablature colour", None))
        self.hideComment.setText(_translate("MainWindow", "Hide", None))
        self.hideChord.setText(_translate("MainWindow", "Hide", None))
        self.hideTab.setText(_translate("MainWindow", "Hide", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_settings), _translate("MainWindow", "Settings", None))
        self.reloadButton.setText(_translate("MainWindow", "Reload", None))
        self.editButton.setText(_translate("MainWindow", "Edit", None))
        self.playButton.setText(_translate("MainWindow", "Play", None))

